### ISSUE TITLE
Whitelist_attributes could be Class Method

### ISSUE THREAD

**Issue by viniciuszago** [fidelisrafael/nifty_services-sinatra_example#4]
I was thinking that constant `WHITELIST_ATTRIBUTES` could be a Class Method like `record_type`
For example, Instead of:

```ruby
WHITELIST_ATTRIBUTES = [:title, :content]

def record_allowed_attributes
   WHITELIST_ATTRIBUTES
  end
```

Could be:

```ruby

whitelist_attributes :title, :content
```

What do you think?

**Comment by fidelisrafael** [comment]
Good ideia! In the next release I will introduce this, if you want to help fell free to send a PR to nifty_services
